{"name": "Негативный тест авторизации", "status": "passed", "parameters": [{"name": "browser_name", "value": "'chromium'"}, {"name": "username", "value": "'rty'"}, {"name": "password", "value": "'vr4r'"}, {"name": "result", "value": "'Invalid credentials. Please try again.'"}], "start": 1738131047250, "stop": 1738131052951, "uuid": "bbfe8e71-4561-4c12-89ec-c4d1d502516d", "historyId": "1b631f0cee5da529f851434cd5038ad8", "testCaseId": "68772be64bb38f6a4c2b59109d7c35bc", "fullName": "test_login#test_login_failure", "labels": [{"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-TR3R9M3"}, {"name": "thread", "value": "8660-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}