{"name": "Негативный тест авторизации", "status": "passed", "steps": [{"name": "Шаг 1. Вводим ложные логин/пароль", "status": "passed", "start": 1738134581491, "stop": 1738134581508}], "parameters": [{"name": "browser_name", "value": "'chromium'"}, {"name": "username", "value": "'rty'"}, {"name": "password", "value": "'vr4r'"}, {"name": "result", "value": "'Invalid credentials. Please try again.'"}], "start": 1738134576743, "stop": 1738134581509, "uuid": "07834fe7-3248-4fd3-8908-82319fb8804e", "historyId": "1b631f0cee5da529f851434cd5038ad8", "testCaseId": "68772be64bb38f6a4c2b59109d7c35bc", "fullName": "test_login#test_login_failure", "labels": [{"name": "story", "value": "Login Feature"}, {"name": "severity", "value": "normal"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-TR3R9M3"}, {"name": "thread", "value": "45524-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}